### ISSUE TITLE
Would it be possible to add some explanations as to why you need this wrapper?

### ISSUE THREAD

**Issue by ITCMD** [fdcastel/Ps.cmd#1]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fdcastel** [comment]
Sure! Why not?


https://github.com/fdcastel/Ps.cmd/blob/master/README.md#why-

Also, see:

https://github.com/fdcastel/Ps.cmd/blob/master/README.md#features



Finally, please let me know if a version in Japanese (or maybe Hungarian) would help.
