### ISSUE TITLE
Parameters with spaces

### ISSUE THREAD

**Issue by Jasonthurston** [fdcastel/Ps.cmd#2]
failed when I tried a parameter like:

-fooparam 'foo bar'

Error Message:
A positional parameter cannot be found that accepts argument 'bar'.

**Comment by fdcastel** [comment]
First rule of quote club: Quotes in cmd.exe **ARE HELL**:

https://stackoverflow.com/questions/19862232/escaping-quotes-in-powershell-exe-via-command-prompt
